version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    #working_directory: ~/repo

    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  
  test:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: echo "testing"
      - run: npm install
      - run: npm test

  workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test